# Generated by Django 5.2.3 on 2025-06-26 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='amount_ml',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
